version: '3.3'

services:
  app:
    build: .
    healthcheck:
      disable: true
    volumes:
      - .:/app
    tty: true
    environment:
     ASANA_WORKSPACE:
     ASANA_STATUS:
     ASANA_API_KEY: